services:
  mudae-bot:
    container_name: mudae-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: "no"
    depends_on:
      - selenium
    networks:
      - "mudaentw"

  selenium:
    container_name: selenium
    restart: "on-failure"
    image: "selenium/standalone-chrome:104.0"
    # image: "seleniarm/standalone-chromium:104.0" # for arm raspberry pi
    ports:
      - "4444:4444"
    networks:
      - "mudaentw"
    hostname: "seleniumweb"

  test:
    container_name: titi
    image: "busybox:latest"
    networks:
      - "mudaentw"
    command: [ "sh", "-c", "while true; do echo hello; sleep 1; done" ]

networks:
  mudaentw:
    driver: bridge